---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-transit
  namespace: demo-transit
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: transit
  serviceName: demo
  template:
    metadata:
      labels:
        demo: transit
    spec:
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi